In [0]:
import json
import os
import pandas as pd
import pprint
import tensorflow as tf
import time
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from keras import backend as K


In [0]:


# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])


In [0]:
vocab_size = 50

encoded_docs = [one_hot(d, vocab_size) for d in docs]

print(encoded_docs)

[[30, 41], [43, 8], [42, 17], [41, 8], [23], [3], [17, 17], [14, 43], [17, 8], [21, 43, 41, 31]]


In [0]:
max_length=4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
print(padded_docs.shape)


[[30 41  0  0]
 [43  8  0  0]
 [42 17  0  0]
 [41  8  0  0]
 [23  0  0  0]
 [ 3  0  0  0]
 [17 17  0  0]
 [14 43  0  0]
 [17  8  0  0]
 [21 43 41 31]]
(10, 4)


In [0]:
def get_model(n_output, vocab_size, max_len):
  #n_input = vocab_size
  inputs = Input(name = 'link', shape = [max_len])
  print(inputs.shape)
  # Embedding the book (shape will be (None, max_len, 10))
  embedding = tf.keras.layers.Embedding(input_dim = 50,
                             output_dim = 10, input_length=max_len)(inputs)
  print(embedding.shape)
  lstm = LSTM(10, return_sequences=True)(embedding)
  flatten = tf.keras.layers.Flatten()(lstm)
  print(lstm.shape)
  dense = tf.keras.layers.Dense(1, activation = 'sigmoid')(flatten)
  
  
  print(dense.shape)
  model = Model(inputs, dense)
  return model

In [0]:
train = get_model(1, 50, 4)

(?, 4)
(?, 4, 10)
(?, 4, 10)
(?, 1)


In [0]:
train.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])


In [0]:
print(padded_docs.shape)
print(labels.shape)
train.fit(padded_docs, labels, epochs=500)

(10, 4)
(10,)
Epoch 1/500
10/10 [==============================] - 0s 626us/step - loss: 0.6466 - acc: 0.9000
Epoch 2/500
10/10 [==============================] - 0s 627us/step - loss: 0.6445 - acc: 0.9000
Epoch 3/500
10/10 [==============================] - 0s 482us/step - loss: 0.6424 - acc: 0.9000
Epoch 4/500
10/10 [==============================] - 0s 564us/step - loss: 0.6401 - acc: 0.9000
Epoch 5/500
10/10 [==============================] - 0s 468us/step - loss: 0.6378 - acc: 0.9000
Epoch 6/500
10/10 [==============================] - 0s 549us/step - loss: 0.6354 - acc: 0.9000
Epoch 7/500
10/10 [==============================] - 0s 470us/step - loss: 0.6330 - acc: 0.9000
Epoch 8/500
10/10 [==============================] - 0s 514us/step - loss: 0.6304 - acc: 0.9000
Epoch 9/500
10/10 [==============================] - 0s 647us/step - loss: 0.6278 - acc: 0.9000
Epoch 10/500
10/10 [==============================] - 0s 506us/step - loss: 0.6250 - acc: 0.9000
Epoch 11/500
10/10 [=====

In [0]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [0]:
from keras.preprocessing.text import Tokenizer
t = Tokenizer()

In [0]:
t.fit_on_texts(docs)

In [0]:
vocab_size = len(t.word_index)+1

In [0]:
ecnoded_docs = t.texts_to_sequences(docs)

In [0]:
print(encoded_docs)

[[30, 41], [43, 8], [42, 17], [41, 8], [23], [3], [17, 17], [14, 43], [17, 8], [21, 43, 41, 31]]


In [0]:
max_length = 4

In [0]:
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

In [0]:
print(padded_docs)

[[30 41  0  0]
 [43  8  0  0]
 [42 17  0  0]
 [41  8  0  0]
 [23  0  0  0]
 [ 3  0  0  0]
 [17 17  0  0]
 [14 43  0  0]
 [17  8  0  0]
 [21 43 41 31]]
